version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambdatatedge-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jxp83wcw6a9a"
s3_prefix = "lambdatatedge-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LogsRetentionInDays=\"7\""
image_repositories = []
